version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    depends_on:
      - redis
      - elasticsearch
    networks:
      - chat-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - chat-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
      - logger.level=WARN
    ports:
      - "9200:9200"
    networks:
      - chat-network
    
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    command: tunnel --url http://backend:3001
    depends_on:
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
